[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LatticeQM = "606d2a7e-9b17-11e9-1c5c-455b84f60309"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
TopologicalNumbers = "82b459e2-751c-486c-8b84-4a85e9d7ad51"
